services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-contatos-php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: desafio-backend-db
    environment:
      POSTGRES_DB: desafio-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: